name: OPEN COLLAR INC.
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62399
title: 'OPEN COLLAR '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#775e49'
    - '#ae9e90'
    - '#cac0b7'
    - '#d6d6d6'
  brandStrength: 1
  lightness: 0.02357395808212459
  saturation: 0.018953889375552535
  rhythmicContrast: 0.7005308424122632
purpose: []
