name: YNOT ENTERPRISES
favicon: null
layout_spectrum: 0.4965554210357368
typography_spectrum: 0.8961067923810333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8719914280809462
  lightness: 0.02357395808212459
  saturation: 0.018953889375552535
  rhythmicContrast: 0.7005308424122632
purpose: []
